# Generated by Django 3.2.6 on 2021-11-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211113_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='owner',
            new_name='user',
        ),
    ]
