# Generated by Django 3.2.6 on 2021-11-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211113_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='housing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='street',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='street',
        ),
        migrations.RemoveField(
            model_name='place',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='housing',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
