# Generated by Django 3.2.6 on 2021-11-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211113_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='houusing',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.housing'),
        ),
    ]
